/**
 * Car definitions — v0.6: per-road-type maxSpeed, no maxSpeedMul
 */

export const CARS = [
  {
    id: 'alpine_white',
    name: 'ALPINE GT',
    team: 'Team Tokamak',
    desc: 'Balanced all-rounder. No weakness, no dominance.',
    color: '#f1faee',
    stats: {
      topSpeed: 6,
      cornering: 6,
      acceleration: 6,
      braking: 6,
      recovery: 6,
    },
    physics: {
      accelMul: 1.0,
      turnMul: 1.0,
      brakeMul: 1.0,
      obstaclePenaltyMul: 1.0,
      offroadMul: 1.0,
      roadMaxSpeed: { paved: 383, dirt: 317, sand: 262, rocky: 231, offroad: 179 },
    },
  },
  {
    id: 'hyper_blue',
    name: 'HYPER-N',
    team: 'Blue Shell Racing',
    desc: 'Extreme top speed. Weak cornering — for brave drivers.',
    color: '#1a8aff',
    stats: {
      topSpeed: 9,
      cornering: 4,
      acceleration: 7,
      braking: 5,
      recovery: 5,
    },
    physics: {
      accelMul: 1.1,
      turnMul: 0.82,
      brakeMul: 0.9,
      obstaclePenaltyMul: 1.0,
      offroadMul: 0.9,
      roadMaxSpeed: { paved: 455, dirt: 345, sand: 276, rocky: 238, offroad: 162 },
    },
  },
  {
    id: 'puma_orange',
    name: 'PUMA RS',
    team: 'M-Sport Rally',
    desc: 'Best cornering & braking. Slower on straights.',
    color: '#ff6b35',
    stats: {
      topSpeed: 5,
      cornering: 9,
      acceleration: 5,
      braking: 8,
      recovery: 5,
    },
    physics: {
      accelMul: 0.95,
      turnMul: 1.2,
      brakeMul: 1.25,
      obstaclePenaltyMul: 1.0,
      offroadMul: 0.95,
      roadMaxSpeed: { paved: 352, dirt: 307, sand: 255, rocky: 224, offroad: 173 },
    },
  },
  {
    id: 'tundra_red',
    name: 'TUNDRA X',
    team: 'Nordic Motorsport',
    desc: 'Tank-like durability. Obstacles barely slow it down.',
    color: '#e63946',
    stats: {
      topSpeed: 5,
      cornering: 5,
      acceleration: 5,
      braking: 6,
      recovery: 10,
    },
    physics: {
      accelMul: 0.95,
      turnMul: 0.95,
      brakeMul: 1.05,
      obstaclePenaltyMul: 0.5,
      offroadMul: 1.3,
      roadMaxSpeed: { paved: 369, dirt: 314, sand: 266, rocky: 238, offroad: 235 },
    },
  },
  {
    id: 'volt_green',
    name: 'VOLT EV',
    team: 'Electra Rally',
    desc: 'Insane acceleration. Burns out at top speed.',
    color: '#2dd4a8',
    stats: {
      topSpeed: 5,
      cornering: 6,
      acceleration: 10,
      braking: 7,
      recovery: 4,
    },
    physics: {
      accelMul: 1.35,
      turnMul: 1.0,
      brakeMul: 1.1,
      obstaclePenaltyMul: 1.15,
      offroadMul: 0.85,
      roadMaxSpeed: { paved: 362, dirt: 300, sand: 252, rocky: 217, offroad: 162 },
    },
  },
];

// Pixel art definitions for each car (20x28 grid, 2x scale = 40x56)
export const CAR_PIXELS = {
  alpine_white: (() => {
    const _=0, W=0xf1faee, Ws=0xd8e8dd, Wd=0xc0d0c5, Wk=0xa8b8ad, R=0xe63946, Rd=0xcc2a38, Rl=0xff5060,
          B=0x1d3557, Bl=0x2a4a6e, Y=0xf4d35e, Yb=0xffe080, D=0x2b2d42, Dd=0x1a1c30,
          G=0x6c757d, Gl=0x8a949c, Gd=0x555565, L=0xa8dadc, Ll=0xc0eef0, O=0xff6b35, Od=0xdd5522,
          M=0x4a4e5e, Sh=0x1a1a2a;
    return [
      [_,_,_,_,_,_,_,Y,Yb,Yb,Yb,Yb,Y,_,_,_,_,_,_,_],
      [_,_,_,_,_,_,Y,Yb,Yb,Yb,Yb,Yb,Yb,Y,_,_,_,_,_,_],
      [_,_,_,_,_,G,Gl,W,W,W,W,W,W,Gl,G,_,_,_,_,_],
      [_,_,_,_,G,Gl,W,Ws,W,W,W,W,Ws,W,Gl,G,_,_,_,_],
      [_,_,_,D,Dd,Gd,W,Ws,R,R,R,R,Ws,W,Gd,Dd,D,_,_,_],
      [_,_,_,D,Dd,B,Bl,B,B,B,B,B,B,Bl,B,Dd,D,_,_,_],
      [_,_,_,D,Dd,B,L,Ll,Ll,Ll,Ll,Ll,Ll,L,B,Dd,D,_,_,_],
      [_,_,_,D,Dd,B,Bl,L,Ll,Ll,Ll,Ll,L,Bl,B,Dd,D,_,_,_],
      [_,_,M,G,Gd,Ws,W,R,Rd,Rd,Rd,Rd,R,W,Ws,Gd,G,M,_,_],
      [_,_,_,G,Wd,Ws,W,R,R,Rd,Rd,R,R,W,Ws,Wd,G,_,_,_],
      [_,_,_,_,Wd,Ws,W,W,R,R,R,R,W,W,Ws,Wd,_,_,_,_],
      [_,_,_,_,Wk,Wd,W,Ws,R,Rl,Rl,R,Ws,W,Wd,Wk,_,_,_,_],
      [_,_,_,_,Wk,Wd,Ws,W,R,R,R,R,W,Ws,Wd,Wk,_,_,_,_],
      [_,_,_,_,Wk,Wd,W,Ws,R,R,R,R,Ws,W,Wd,Wk,_,_,_,_],
      [_,_,_,_,Wk,Wd,Ws,W,R,Rl,Rl,R,W,Ws,Wd,Wk,_,_,_,_],
      [_,_,_,_,Wk,Wd,W,W,R,R,R,R,W,W,Ws,Wd,_,_,_,_],
      [_,_,_,_,Wd,Ws,W,Ws,Rd,R,R,Rd,Ws,W,Ws,Wd,_,_,_,_],
      [_,_,_,G,Wd,Ws,W,R,R,Rd,Rd,R,R,W,Ws,Wd,G,_,_,_],
      [_,_,M,G,Gd,Ws,W,R,Rd,Rd,Rd,Rd,R,W,Ws,Gd,G,M,_,_],
      [_,_,_,D,Dd,Gd,W,Ws,R,R,R,R,Ws,W,Gd,Dd,D,_,_,_],
      [_,_,_,D,Dd,W,Ws,W,R,R,R,R,W,Ws,W,Dd,D,_,_,_],
      [_,_,_,D,Dd,Ws,W,W,W,W,W,W,W,W,Ws,Dd,D,_,_,_],
      [_,_,_,D,Dd,Wd,Ws,Ws,Ws,Ws,Ws,Ws,Ws,Ws,Wd,Dd,D,_,_,_],
      [_,_,_,D,Dd,Wk,Wd,Ws,Ws,W,W,Ws,Ws,Wd,Wk,Dd,D,_,_,_],
      [_,_,_,_,G,Gl,O,Gd,G,G,G,G,Gd,O,Gl,G,_,_,_,_],
      [_,_,_,_,_,G,Od,O,O,Gd,Gd,O,O,Od,G,_,_,_,_,_],
      [_,_,_,_,_,_,Od,Rd,_,Sh,Sh,_,Rd,Od,_,_,_,_,_,_],
      [_,_,_,_,_,_,_,Sh,_,_,_,_,Sh,_,_,_,_,_,_,_],
    ];
  })(),
  hyper_blue: (() => {
    const _=0, Bl=0x1a8aff, Bm=0x0a6add, Bd=0x0a5acc, Bk=0x0a3a88, Bkd=0x062a66,
          Bh=0x55aaff, Blg=0x88bbff, Bx=0x3399ff, W=0xffffff, R=0xe63946, Rd=0xcc2a38,
          D=0x2b2d42, Dd=0x1a1c30, G=0x555566, Gl=0x6a6a7a, Gd=0x444455,
          Y=0xf4d35e, Yb=0xffe080, M=0x3a3a4e, Sh=0x1a1a2a;
    return [
      [_,_,_,_,_,_,_,Y,Yb,Yb,Yb,Yb,Y,_,_,_,_,_,_,_],
      [_,_,_,_,_,_,Y,Yb,Yb,Yb,Yb,Yb,Yb,Y,_,_,_,_,_,_],
      [_,_,_,_,_,G,Gl,Bl,Bh,Bh,Bh,Bh,Bl,Gl,G,_,_,_,_,_],
      [_,_,_,_,G,Gl,Bl,Bh,Blg,Blg,Blg,Blg,Bh,Bl,Gl,G,_,_,_,_],
      [_,_,_,D,Dd,Gd,Bl,Bh,W,W,W,W,Bh,Bl,Gd,Dd,D,_,_,_],
      [_,_,_,D,Dd,Bk,Bkd,Bk,Bk,Bk,Bk,Bk,Bk,Bkd,Bk,Dd,D,_,_,_],
      [_,_,_,D,Dd,Bk,Blg,Blg,Blg,Blg,Blg,Blg,Blg,Blg,Bk,Dd,D,_,_,_],
      [_,_,_,D,Dd,Bk,Bkd,Blg,Bx,Bx,Bx,Bx,Blg,Bkd,Bk,Dd,D,_,_,_],
      [_,_,M,G,Gd,Bl,Bm,R,R,R,R,R,R,Bm,Bl,Gd,G,M,_,_],
      [_,_,_,G,Bd,Bl,Bm,Rd,Rd,Bm,Bm,Rd,Rd,Bm,Bl,Bd,G,_,_,_],
      [_,_,_,_,Bd,Bl,Bm,Bm,Bl,Bh,Bh,Bl,Bm,Bm,Bl,Bd,_,_,_,_],
      [_,_,_,_,Bkd,Bd,Bl,Bh,Blg,Bh,Bh,Blg,Bh,Bl,Bd,Bkd,_,_,_,_],
      [_,_,_,_,Bkd,Bd,Bm,Bl,Bh,Bh,Bh,Bh,Bl,Bm,Bd,Bkd,_,_,_,_],
      [_,_,_,_,Bkd,Bd,Bl,Bm,Bl,Bx,Bx,Bl,Bm,Bl,Bd,Bkd,_,_,_,_],
      [_,_,_,_,Bkd,Bd,Bm,Bl,Bh,Bh,Bh,Bh,Bl,Bm,Bd,Bkd,_,_,_,_],
      [_,_,_,_,Bd,Bl,Bm,Bm,Bl,Bh,Bh,Bl,Bm,Bm,Bl,Bd,_,_,_,_],
      [_,_,_,_,Bd,Bl,Bm,Bl,Rd,Bm,Bm,Rd,Bl,Bm,Bl,Bd,_,_,_,_],
      [_,_,_,G,Bd,Bl,Bm,R,R,Rd,Rd,R,R,Bm,Bl,Bd,G,_,_,_],
      [_,_,M,G,Gd,Bl,Bm,R,R,R,R,R,R,Bm,Bl,Gd,G,M,_,_],
      [_,_,_,D,Dd,Gd,Bl,Bl,Bh,Bh,Bh,Bh,Bl,Bl,Gd,Dd,D,_,_,_],
      [_,_,_,D,Dd,Bl,Bm,R,R,Bm,Bm,R,R,Bm,Bl,Dd,D,_,_,_],
      [_,_,_,D,Dd,Bd,Bl,Bl,Bl,Bl,Bl,Bl,Bl,Bl,Bd,Dd,D,_,_,_],
      [_,_,_,D,Dd,Bkd,Bd,Bd,Bd,Bd,Bd,Bd,Bd,Bd,Bkd,Dd,D,_,_,_],
      [_,_,_,D,Dd,Bkd,Bkd,Bd,Bm,Bd,Bd,Bm,Bd,Bkd,Bkd,Dd,D,_,_,_],
      [_,_,_,_,G,Gl,R,Gd,G,G,G,G,Gd,R,Gl,G,_,_,_,_],
      [_,_,_,_,_,G,Rd,R,R,Gd,Gd,R,R,Rd,G,_,_,_,_,_],
      [_,_,_,_,_,_,Rd,Rd,_,Sh,Sh,_,Rd,Rd,_,_,_,_,_,_],
      [_,_,_,_,_,_,_,Sh,_,_,_,_,Sh,_,_,_,_,_,_,_],
    ];
  })(),
  puma_orange: (() => {
    const _=0, O=0xff6b35, Om=0xee5a28, Od=0xcc5020, Ob=0xff8855, Oh=0xffaa77, Ox=0xff9966,
          W=0xffffff, Wg=0xeeeeff, Blk=0x1a3a6a, Bld=0x0a2a55, Blg=0x6688aa,
          D=0x2b2d42, Dd=0x1a1c30, G=0x555566, Gl=0x6a6a7a, Gd=0x444455,
          Y=0xf4d35e, Yb=0xffe080, M=0x4a3a2e, Sh=0x1a1a2a;
    return [
      [_,_,_,_,_,_,_,Y,Yb,Yb,Yb,Yb,Y,_,_,_,_,_,_,_],
      [_,_,_,_,_,_,Y,Yb,Yb,Yb,Yb,Yb,Yb,Y,_,_,_,_,_,_],
      [_,_,_,_,_,G,Gl,O,Oh,Oh,Oh,Oh,O,Gl,G,_,_,_,_,_],
      [_,_,_,_,G,Gl,O,Oh,Ox,Ox,Ox,Ox,Oh,O,Gl,G,_,_,_,_],
      [_,_,_,D,Dd,Gd,O,Oh,Blk,Blk,Blk,Blk,Oh,O,Gd,Dd,D,_,_,_],
      [_,_,_,D,Dd,Blk,Bld,Blk,Blk,Blk,Blk,Blk,Blk,Bld,Blk,Dd,D,_,_,_],
      [_,_,_,D,Dd,Blk,Blg,Blg,Blg,Blg,Blg,Blg,Blg,Blg,Blk,Dd,D,_,_,_],
      [_,_,_,D,Dd,Blk,Bld,Blg,Blg,Blg,Blg,Blg,Blg,Bld,Blk,Dd,D,_,_,_],
      [_,_,M,G,Gd,O,Ob,Oh,Oh,W,W,Oh,Oh,Ob,O,Gd,G,M,_,_],
      [_,_,_,G,Od,O,Ob,W,W,Ob,Ob,W,W,Ob,O,Od,G,_,_,_],
      [_,_,_,_,Od,O,Om,Om,O,Oh,Oh,O,Om,Om,O,Od,_,_,_,_],
      [_,_,_,_,Od,O,O,Oh,Ox,Oh,Oh,Ox,Oh,O,O,Od,_,_,_,_],
      [_,_,_,_,Od,Om,O,O,Oh,Oh,Oh,Oh,O,O,Om,Od,_,_,_,_],
      [_,_,_,_,Od,O,Ob,Oh,O,Ox,Ox,O,Oh,Ob,O,Od,_,_,_,_],
      [_,_,_,_,Od,O,O,Oh,Ox,Oh,Oh,Ox,Oh,O,O,Od,_,_,_,_],
      [_,_,_,_,Od,O,Om,Om,O,Oh,Oh,O,Om,Om,O,Od,_,_,_,_],
      [_,_,_,_,Od,O,Ob,W,W,Ob,Ob,W,W,Ob,O,Od,_,_,_,_],
      [_,_,_,G,Od,O,Ob,Oh,Oh,W,W,Oh,Oh,Ob,O,Od,G,_,_,_],
      [_,_,M,G,Gd,O,Ob,Oh,Oh,Ob,Ob,Oh,Oh,Ob,O,Gd,G,M,_,_],
      [_,_,_,D,Dd,Gd,O,O,Oh,Oh,Oh,Oh,O,O,Gd,Dd,D,_,_,_],
      [_,_,_,D,Dd,O,Om,Ob,Ob,Om,Om,Ob,Ob,Om,O,Dd,D,_,_,_],
      [_,_,_,D,Dd,Od,O,O,O,O,O,O,O,O,Od,Dd,D,_,_,_],
      [_,_,_,D,Dd,Od,Od,Om,Om,Od,Od,Om,Om,Od,Od,Dd,D,_,_,_],
      [_,_,_,D,Dd,Od,Od,Od,Om,Om,Om,Om,Od,Od,Od,Dd,D,_,_,_],
      [_,_,_,_,G,Gl,Wg,Gd,G,G,G,G,Gd,Wg,Gl,G,_,_,_,_],
      [_,_,_,_,_,G,W,Wg,Wg,Gd,Gd,Wg,Wg,W,G,_,_,_,_,_],
      [_,_,_,_,_,_,W,W,_,Sh,Sh,_,W,W,_,_,_,_,_,_],
      [_,_,_,_,_,_,_,Sh,_,_,_,_,Sh,_,_,_,_,_,_,_],
    ];
  })(),
  tundra_red: (() => {
    const _=0, R=0xe63946, Rm=0xd42d3a, Rd=0xb02030, Rb=0xff5566, Rh=0xff7788, Rx=0xff8899,
          W=0xffffff, Bk=0x1a1a2e, Bkd=0x0e0e1e, Bkg=0x8888aa,
          D=0x2b2d42, Dd=0x1a1c30, G=0x555566, Gl=0x6a6a7a, Gd=0x444455,
          Y=0xf4d35e, Yb=0xffe080, M=0x3a2a2e, Sh=0x1a1a2a;
    return [
      [_,_,_,_,_,_,_,Y,Yb,Yb,Yb,Yb,Y,_,_,_,_,_,_,_],
      [_,_,_,_,_,_,Y,Yb,Yb,Yb,Yb,Yb,Yb,Y,_,_,_,_,_,_],
      [_,_,_,_,_,G,Gl,R,Rh,Rh,Rh,Rh,R,Gl,G,_,_,_,_,_],
      [_,_,_,_,G,Gl,R,Rh,Rx,Rx,Rx,Rx,Rh,R,Gl,G,_,_,_,_],
      [_,_,_,D,Dd,Gd,R,Rb,W,W,W,W,Rb,R,Gd,Dd,D,_,_,_],
      [_,_,_,D,Dd,Bk,Bkd,Bk,Bk,Bk,Bk,Bk,Bk,Bkd,Bk,Dd,D,_,_,_],
      [_,_,_,D,Dd,Bk,Bkg,Bkg,Bkg,Bkg,Bkg,Bkg,Bkg,Bkg,Bk,Dd,D,_,_,_],
      [_,_,_,D,Dd,Bk,Bkd,Bkg,Bkg,Bkg,Bkg,Bkg,Bkg,Bkd,Bk,Dd,D,_,_,_],
      [_,_,M,G,Gd,R,Rb,W,W,Rb,Rb,W,W,Rb,R,Gd,G,M,_,_],
      [_,_,_,G,Rd,R,Rm,Rm,R,Rm,Rm,R,Rm,Rm,R,Rd,G,_,_,_],
      [_,_,_,_,Rd,R,W,W,R,Rh,Rh,R,W,W,R,Rd,_,_,_,_],
      [_,_,_,_,Rd,Rm,R,R,Rm,R,R,Rm,R,R,Rm,Rd,_,_,_,_],
      [_,_,_,_,Rd,R,Rb,Rb,R,Rh,Rh,R,Rb,Rb,R,Rd,_,_,_,_],
      [_,_,_,_,Rd,Rm,R,R,Rm,R,R,Rm,R,R,Rm,Rd,_,_,_,_],
      [_,_,_,_,Rd,R,Rb,Rb,R,Rh,Rh,R,Rb,Rb,R,Rd,_,_,_,_],
      [_,_,_,_,Rd,R,W,W,R,Rh,Rh,R,W,W,R,Rd,_,_,_,_],
      [_,_,_,_,Rd,Rm,Rm,R,Rd,R,R,Rd,R,Rm,Rm,Rd,_,_,_,_],
      [_,_,_,G,Rd,R,Rm,R,R,Rd,Rd,R,R,Rm,R,Rd,G,_,_,_],
      [_,_,M,G,Gd,R,Rb,W,W,Rb,Rb,W,W,Rb,R,Gd,G,M,_,_],
      [_,_,_,D,Dd,Gd,R,R,Rb,Rb,Rb,Rb,R,R,Gd,Dd,D,_,_,_],
      [_,_,_,D,Dd,R,Rm,W,W,Rm,Rm,W,W,Rm,R,Dd,D,_,_,_],
      [_,_,_,D,Dd,Rd,R,R,R,R,R,R,R,R,Rd,Dd,D,_,_,_],
      [_,_,_,D,Dd,Rd,Rd,Rm,Rm,Rd,Rd,Rm,Rm,Rd,Rd,Dd,D,_,_,_],
      [_,_,_,D,Dd,Rd,Rd,Rd,Rm,Rm,Rm,Rm,Rd,Rd,Rd,Dd,D,_,_,_],
      [_,_,_,_,G,Gl,Rh,Gd,G,G,G,G,Gd,Rh,Gl,G,_,_,_,_],
      [_,_,_,_,_,G,Rb,Rh,Rh,Gd,Gd,Rh,Rh,Rb,G,_,_,_,_,_],
      [_,_,_,_,_,_,Rb,Rb,_,Sh,Sh,_,Rb,Rb,_,_,_,_,_,_],
      [_,_,_,_,_,_,_,Sh,_,_,_,_,Sh,_,_,_,_,_,_,_],
    ];
  })(),
  volt_green: (() => {
    const _=0, Gr=0x2dd4a8, Gm=0x22bb95, Gd2=0x1aaa80, Gb=0x55ffcc, Gh=0x77ffdd, Gx=0x44eebb,
          W=0xffffff, Wg=0xeeffee, Bk=0x1a2a2a, Bkd=0x0e1e1e, Bkg=0x88ddcc,
          D=0x2b2d42, Dd=0x1a1c30, G=0x555566, Gl=0x6a6a7a, Gd=0x444455,
          Y=0xf4d35e, Yb=0xffe080, M=0x2a3a3e, Sh=0x1a1a2a;
    return [
      [_,_,_,_,_,_,_,Y,Yb,Yb,Yb,Yb,Y,_,_,_,_,_,_,_],
      [_,_,_,_,_,_,Y,Yb,Yb,Yb,Yb,Yb,Yb,Y,_,_,_,_,_,_],
      [_,_,_,_,_,G,Gl,Gr,Gh,Gh,Gh,Gh,Gr,Gl,G,_,_,_,_,_],
      [_,_,_,_,G,Gl,Gr,Gh,Gx,Gx,Gx,Gx,Gh,Gr,Gl,G,_,_,_,_],
      [_,_,_,D,Dd,Gd,Gr,Gb,Bk,Bk,Bk,Bk,Gb,Gr,Gd,Dd,D,_,_,_],
      [_,_,_,D,Dd,Bk,Bkd,Bk,Bk,Bk,Bk,Bk,Bk,Bkd,Bk,Dd,D,_,_,_],
      [_,_,_,D,Dd,Bk,Bkg,Bkg,Bkg,Bkg,Bkg,Bkg,Bkg,Bkg,Bk,Dd,D,_,_,_],
      [_,_,_,D,Dd,Bk,Bkd,Bkg,Bkg,Bkg,Bkg,Bkg,Bkg,Bkd,Bk,Dd,D,_,_,_],
      [_,_,M,G,Gd,Gr,Gb,Gh,Gh,Gb,Gb,Gh,Gh,Gb,Gr,Gd,G,M,_,_],
      [_,_,_,G,Gd2,Gr,Gm,Gm,Gr,Gm,Gm,Gr,Gm,Gm,Gr,Gd2,G,_,_,_],
      [_,_,_,_,Gd2,Gr,W,W,Gr,Gh,Gh,Gr,W,W,Gr,Gd2,_,_,_,_],
      [_,_,_,_,Gd2,Gm,Gr,Gr,Gm,Gr,Gr,Gm,Gr,Gr,Gm,Gd2,_,_,_,_],
      [_,_,_,_,Gd2,Gr,Gb,Gb,Gr,Gx,Gx,Gr,Gb,Gb,Gr,Gd2,_,_,_,_],
      [_,_,_,_,Gd2,Gm,Gr,Gr,Gm,Gr,Gr,Gm,Gr,Gr,Gm,Gd2,_,_,_,_],
      [_,_,_,_,Gd2,Gr,Gb,Gb,Gr,Gx,Gx,Gr,Gb,Gb,Gr,Gd2,_,_,_,_],
      [_,_,_,_,Gd2,Gr,W,W,Gr,Gh,Gh,Gr,W,W,Gr,Gd2,_,_,_,_],
      [_,_,_,_,Gd2,Gm,Gm,Gr,Gd2,Gr,Gr,Gd2,Gr,Gm,Gm,Gd2,_,_,_,_],
      [_,_,_,G,Gd2,Gr,Gm,Gr,Gr,Gd2,Gd2,Gr,Gr,Gm,Gr,Gd2,G,_,_,_],
      [_,_,M,G,Gd,Gr,Gb,Gh,Gh,Gb,Gb,Gh,Gh,Gb,Gr,Gd,G,M,_,_],
      [_,_,_,D,Dd,Gd,Gr,Gr,Gb,Gb,Gb,Gb,Gr,Gr,Gd,Dd,D,_,_,_],
      [_,_,_,D,Dd,Gr,Gm,Gb,Gb,Gm,Gm,Gb,Gb,Gm,Gr,Dd,D,_,_,_],
      [_,_,_,D,Dd,Gd2,Gr,Gr,Gr,Gr,Gr,Gr,Gr,Gr,Gd2,Dd,D,_,_,_],
      [_,_,_,D,Dd,Gd2,Gd2,Gm,Gm,Gd2,Gd2,Gm,Gm,Gd2,Gd2,Dd,D,_,_,_],
      [_,_,_,D,Dd,Gd2,Gd2,Gd2,Gm,Gm,Gm,Gm,Gd2,Gd2,Gd2,Dd,D,_,_,_],
      [_,_,_,_,G,Gl,Wg,Gd,G,G,G,G,Gd,Wg,Gl,G,_,_,_,_],
      [_,_,_,_,_,G,W,Wg,Wg,Gd,Gd,Wg,Wg,W,G,_,_,_,_,_],
      [_,_,_,_,_,_,W,W,_,Sh,Sh,_,W,W,_,_,_,_,_,_],
      [_,_,_,_,_,_,_,Sh,_,_,_,_,Sh,_,_,_,_,_,_,_],
    ];
  })(),
};
