/**
 * Car definitions — v0.6: per-road-type maxSpeed, no maxSpeedMul
 */

export const CARS = [
  {
    id: 'alpine_white',
    name: 'ALPINE GT',
    team: 'Team Tokamak',
    desc: 'Balanced all-rounder. No weakness, no dominance.',
    color: '#f1faee',
    stats: {
      topSpeed: 6,
      cornering: 6,
      acceleration: 6,
      braking: 6,
      recovery: 6,
    },
    physics: {
      accelMul: 1.0,
      turnMul: 1.0,
      brakeMul: 1.0,
      obstaclePenaltyMul: 1.0,
      offroadMul: 1.0,
      roadMaxSpeed: { paved: 383, dirt: 317, sand: 262, rocky: 231, offroad: 179 },
    },
  },
  {
    id: 'hyper_blue',
    name: 'HYPER-N',
    team: 'Blue Shell Racing',
    desc: 'Extreme top speed. Weak cornering — for brave drivers.',
    color: '#1a8aff',
    stats: {
      topSpeed: 9,
      cornering: 4,
      acceleration: 7,
      braking: 5,
      recovery: 5,
    },
    physics: {
      accelMul: 1.1,
      turnMul: 0.82,
      brakeMul: 0.9,
      obstaclePenaltyMul: 1.0,
      offroadMul: 0.9,
      roadMaxSpeed: { paved: 455, dirt: 345, sand: 276, rocky: 238, offroad: 162 },
    },
  },
  {
    id: 'puma_orange',
    name: 'PUMA RS',
    team: 'M-Sport Rally',
    desc: 'Best cornering & braking. Slower on straights.',
    color: '#ff6b35',
    stats: {
      topSpeed: 5,
      cornering: 9,
      acceleration: 5,
      braking: 8,
      recovery: 5,
    },
    physics: {
      accelMul: 0.95,
      turnMul: 1.2,
      brakeMul: 1.25,
      obstaclePenaltyMul: 1.0,
      offroadMul: 0.95,
      roadMaxSpeed: { paved: 352, dirt: 307, sand: 255, rocky: 224, offroad: 173 },
    },
  },
  {
    id: 'tundra_red',
    name: 'TUNDRA X',
    team: 'Nordic Motorsport',
    desc: 'Tank-like durability. Obstacles barely slow it down.',
    color: '#e63946',
    stats: {
      topSpeed: 5,
      cornering: 5,
      acceleration: 5,
      braking: 6,
      recovery: 10,
    },
    physics: {
      accelMul: 0.95,
      turnMul: 0.95,
      brakeMul: 1.05,
      obstaclePenaltyMul: 0.5,
      offroadMul: 1.3,
      roadMaxSpeed: { paved: 369, dirt: 314, sand: 266, rocky: 238, offroad: 235 },
    },
  },
  {
    id: 'volt_green',
    name: 'VOLT EV',
    team: 'Electra Rally',
    desc: 'Insane acceleration. Burns out at top speed.',
    color: '#2dd4a8',
    stats: {
      topSpeed: 5,
      cornering: 6,
      acceleration: 10,
      braking: 7,
      recovery: 4,
    },
    physics: {
      accelMul: 1.35,
      turnMul: 1.0,
      brakeMul: 1.1,
      obstaclePenaltyMul: 1.15,
      offroadMul: 0.85,
      roadMaxSpeed: { paved: 362, dirt: 300, sand: 252, rocky: 217, offroad: 162 },
    },
  },
];

// Pixel art definitions for each car (14x20 grid, 2x scale = 28x40)
export const CAR_PIXELS = {
  alpine_white: (() => {
    const _=0, W=0xf1faee, Ws=0xd8e8dd, Wd=0xc0d0c5, R=0xe63946, Rd=0xcc2a38,
          B=0x1d3557, Bl=0x2a4a6e, Y=0xf4d35e, Yb=0xffe080, D=0x2b2d42, Dd=0x1a1c30,
          G=0x6c757d, Gl=0x8a949c, L=0xa8dadc, Ll=0xc0eef0, O=0xff6b35, Od=0xdd5522,
          M=0x4a4e5e;
    return [
      [_,_,_,_,_,Y,Yb,Yb,Y,_,_,_,_,_],
      [_,_,_,_,Y,Yb,Yb,Yb,Yb,Y,_,_,_,_],
      [_,_,_,G,Gl,W,W,W,W,Gl,G,_,_,_],
      [_,_,D,Dd,W,Ws,R,R,Ws,W,Dd,D,_,_],
      [_,_,D,Dd,B,Bl,B,B,Bl,B,Dd,D,_,_],
      [_,_,D,Dd,B,L,Ll,Ll,L,B,Dd,D,_,_],
      [_,_,M,G,Ws,W,R,R,W,Ws,G,M,_,_],
      [_,_,_,G,Ws,W,Rd,Rd,W,Ws,G,_,_,_],
      [_,_,_,_,Wd,W,R,R,W,Wd,_,_,_,_],
      [_,_,_,_,Wd,W,R,R,W,Wd,_,_,_,_],
      [_,_,_,_,Wd,Ws,R,R,Ws,Wd,_,_,_,_],
      [_,_,_,_,Wd,W,R,R,W,Wd,_,_,_,_],
      [_,_,M,G,Ws,W,Rd,Rd,W,Ws,G,M,_,_],
      [_,_,D,Dd,W,Ws,R,R,Ws,W,Dd,D,_,_],
      [_,_,D,Dd,W,W,R,R,W,W,Dd,D,_,_],
      [_,_,D,Dd,Ws,W,W,W,W,Ws,Dd,D,_,_],
      [_,_,D,Dd,Wd,Ws,Ws,Ws,Ws,Wd,Dd,D,_,_],
      [_,_,_,G,Gl,O,G,G,O,Gl,G,_,_,_],
      [_,_,_,_,G,Od,O,O,Od,G,_,_,_,_],
      [_,_,_,_,_,Od,_,_,Od,_,_,_,_,_],
    ];
  })(),
  hyper_blue: (() => {
    const _=0, Bl=0x1a8aff, Bm=0x0a6add, Bd=0x0a5acc, Bk=0x0a3a88, Bkd=0x062a66,
          Bh=0x55aaff, Blg=0x88bbff, W=0xffffff, R=0xe63946, Rd=0xcc2a38,
          D=0x2b2d42, Dd=0x1a1c30, G=0x555566, Gl=0x6a6a7a, Y=0xf4d35e, Yb=0xffe080,
          M=0x3a3a4e;
    return [
      [_,_,_,_,_,Y,Yb,Yb,Y,_,_,_,_,_],
      [_,_,_,_,Y,Yb,Yb,Yb,Yb,Y,_,_,_,_],
      [_,_,_,G,Gl,Bl,Bh,Bh,Bl,Gl,G,_,_,_],
      [_,_,D,Dd,Bl,Bh,W,W,Bh,Bl,Dd,D,_,_],
      [_,_,D,Dd,Bk,Bkd,Bk,Bk,Bkd,Bk,Dd,D,_,_],
      [_,_,D,Dd,Bk,Blg,Blg,Blg,Blg,Bk,Dd,D,_,_],
      [_,_,M,G,Bl,Bm,R,R,Bm,Bl,G,M,_,_],
      [_,_,_,G,Bl,Bm,Rd,Rd,Bm,Bl,G,_,_,_],
      [_,_,_,_,Bd,Bl,Bm,Bm,Bl,Bd,_,_,_,_],
      [_,_,_,_,Bd,Bl,Bh,Bh,Bl,Bd,_,_,_,_],
      [_,_,_,_,Bd,Bm,Bl,Bl,Bm,Bd,_,_,_,_],
      [_,_,_,_,Bd,Bl,Bm,Bm,Bl,Bd,_,_,_,_],
      [_,_,M,G,Bl,Bm,R,R,Bm,Bl,G,M,_,_],
      [_,_,D,Dd,Bl,Bl,Bh,Bh,Bl,Bl,Dd,D,_,_],
      [_,_,D,Dd,Bl,Bm,R,R,Bm,Bl,Dd,D,_,_],
      [_,_,D,Dd,Bd,Bl,Bl,Bl,Bl,Bd,Dd,D,_,_],
      [_,_,D,Dd,Bkd,Bd,Bd,Bd,Bd,Bkd,Dd,D,_,_],
      [_,_,_,G,Gl,R,G,G,R,Gl,G,_,_,_],
      [_,_,_,_,G,Rd,R,R,Rd,G,_,_,_,_],
      [_,_,_,_,_,Rd,_,_,Rd,_,_,_,_,_],
    ];
  })(),
  puma_orange: (() => {
    const _=0, O=0xff6b35, Om=0xee5a28, Od=0xcc5020, Ob=0xff8855, Oh=0xffaa77,
          W=0xffffff, Wg=0xeeeeff, Blk=0x1a3a6a, Bld=0x0a2a55, Blg=0x6688aa,
          D=0x2b2d42, Dd=0x1a1c30, G=0x555566, Gl=0x6a6a7a, Y=0xf4d35e, Yb=0xffe080,
          M=0x4a3a2e;
    return [
      [_,_,_,_,_,Y,Yb,Yb,Y,_,_,_,_,_],
      [_,_,_,_,Y,Yb,Yb,Yb,Yb,Y,_,_,_,_],
      [_,_,_,G,Gl,O,Oh,Oh,O,Gl,G,_,_,_],
      [_,_,D,Dd,O,Oh,Blk,Blk,Oh,O,Dd,D,_,_],
      [_,_,D,Dd,Blk,Bld,Blk,Blk,Bld,Blk,Dd,D,_,_],
      [_,_,D,Dd,Blk,Blg,Blg,Blg,Blg,Blk,Dd,D,_,_],
      [_,_,M,G,O,Ob,Oh,Oh,Ob,O,G,M,_,_],
      [_,_,_,G,O,Ob,W,W,Ob,O,G,_,_,_],
      [_,_,_,_,Od,O,Om,Om,O,Od,_,_,_,_],
      [_,_,_,_,Od,O,Oh,Oh,O,Od,_,_,_,_],
      [_,_,_,_,Od,Om,O,O,Om,Od,_,_,_,_],
      [_,_,_,_,Od,O,Ob,Ob,O,Od,_,_,_,_],
      [_,_,M,G,O,Ob,Oh,Oh,Ob,O,G,M,_,_],
      [_,_,D,Dd,O,O,W,W,O,O,Dd,D,_,_],
      [_,_,D,Dd,O,Om,Ob,Ob,Om,O,Dd,D,_,_],
      [_,_,D,Dd,Od,O,O,O,O,Od,Dd,D,_,_],
      [_,_,D,Dd,Od,Od,Om,Om,Od,Od,Dd,D,_,_],
      [_,_,_,G,Gl,Wg,G,G,Wg,Gl,G,_,_,_],
      [_,_,_,_,G,W,Wg,Wg,W,G,_,_,_,_],
      [_,_,_,_,_,W,_,_,W,_,_,_,_,_],
    ];
  })(),
  tundra_red: (() => {
    const _=0, R=0xe63946, Rm=0xd42d3a, Rd=0xb02030, Rb=0xff5566, Rh=0xff7788,
          W=0xffffff, Wg=0xeeeeff, Bk=0x1a1a2e, Bkd=0x0e0e1e, Bkg=0x8888aa,
          D=0x2b2d42, Dd=0x1a1c30, G=0x555566, Gl=0x6a6a7a, Y=0xf4d35e, Yb=0xffe080,
          M=0x3a2a2e;
    return [
      [_,_,_,_,_,Y,Yb,Yb,Y,_,_,_,_,_],
      [_,_,_,_,Y,Yb,Yb,Yb,Yb,Y,_,_,_,_],
      [_,_,_,G,Gl,R,Rh,Rh,R,Gl,G,_,_,_],
      [_,_,D,Dd,R,Rb,W,W,Rb,R,Dd,D,_,_],
      [_,_,D,Dd,Bk,Bkd,Bk,Bk,Bkd,Bk,Dd,D,_,_],
      [_,_,D,Dd,Bk,Bkg,Bkg,Bkg,Bkg,Bk,Dd,D,_,_],
      [_,_,M,G,R,Rb,W,W,Rb,R,G,M,_,_],
      [_,_,_,G,Rd,R,Rm,Rm,R,Rd,G,_,_,_],
      [_,_,_,_,Rd,R,W,W,R,Rd,_,_,_,_],
      [_,_,_,_,Rd,Rm,R,R,Rm,Rd,_,_,_,_],
      [_,_,_,_,Rd,R,Rb,Rb,R,Rd,_,_,_,_],
      [_,_,_,_,Rd,Rm,R,R,Rm,Rd,_,_,_,_],
      [_,_,M,G,R,Rb,W,W,Rb,R,G,M,_,_],
      [_,_,D,Dd,R,R,Rb,Rb,R,R,Dd,D,_,_],
      [_,_,D,Dd,R,Rm,W,W,Rm,R,Dd,D,_,_],
      [_,_,D,Dd,Rd,R,R,R,R,Rd,Dd,D,_,_],
      [_,_,D,Dd,Rd,Rd,Rm,Rm,Rd,Rd,Dd,D,_,_],
      [_,_,_,G,Gl,Rh,G,G,Rh,Gl,G,_,_,_],
      [_,_,_,_,G,Rb,Rh,Rh,Rb,G,_,_,_,_],
      [_,_,_,_,_,Rb,_,_,Rb,_,_,_,_,_],
    ];
  })(),
  volt_green: (() => {
    const _=0, Gr=0x2dd4a8, Gm=0x22bb95, Gd=0x1aaa80, Gb=0x55ffcc, Gh=0x77ffdd,
          W=0xffffff, Wg=0xeeffee, Bk=0x1a2a2a, Bkd=0x0e1e1e, Bkg=0x88ddcc,
          D=0x2b2d42, Dd=0x1a1c30, G=0x555566, Gl=0x6a6a7a, Y=0xf4d35e, Yb=0xffe080,
          M=0x2a3a3e;
    return [
      [_,_,_,_,_,Y,Yb,Yb,Y,_,_,_,_,_],
      [_,_,_,_,Y,Yb,Yb,Yb,Yb,Y,_,_,_,_],
      [_,_,_,G,Gl,Gr,Gh,Gh,Gr,Gl,G,_,_,_],
      [_,_,D,Dd,Gr,Gb,Bk,Bk,Gb,Gr,Dd,D,_,_],
      [_,_,D,Dd,Bk,Bkd,Bk,Bk,Bkd,Bk,Dd,D,_,_],
      [_,_,D,Dd,Bk,Bkg,Bkg,Bkg,Bkg,Bk,Dd,D,_,_],
      [_,_,M,G,Gr,Gb,Gh,Gh,Gb,Gr,G,M,_,_],
      [_,_,_,G,Gd,Gr,Gm,Gm,Gr,Gd,G,_,_,_],
      [_,_,_,_,Gd,Gr,W,W,Gr,Gd,_,_,_,_],
      [_,_,_,_,Gd,Gm,Gr,Gr,Gm,Gd,_,_,_,_],
      [_,_,_,_,Gd,Gr,Gb,Gb,Gr,Gd,_,_,_,_],
      [_,_,_,_,Gd,Gm,Gr,Gr,Gm,Gd,_,_,_,_],
      [_,_,M,G,Gr,Gb,Gh,Gh,Gb,Gr,G,M,_,_],
      [_,_,D,Dd,Gr,Gr,Gb,Gb,Gr,Gr,Dd,D,_,_],
      [_,_,D,Dd,Gr,Gm,Gb,Gb,Gm,Gr,Dd,D,_,_],
      [_,_,D,Dd,Gd,Gr,Gr,Gr,Gr,Gd,Dd,D,_,_],
      [_,_,D,Dd,Gd,Gd,Gm,Gm,Gd,Gd,Dd,D,_,_],
      [_,_,_,G,Gl,Wg,G,G,Wg,Gl,G,_,_,_],
      [_,_,_,_,G,W,Wg,Wg,W,G,_,_,_,_],
      [_,_,_,_,_,W,_,_,W,_,_,_,_,_],
    ];
  })(),
};
